# Generated by Django 6.1.1 on 2026-09-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando"),
                            ("em_andamento", "Em andamento"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="aguardando",
                        max_length=20,
                    ),
                ),
                ("jogador1_id", models.IntegerField(blank=True, null=True)),
                ("jogador2_id", models.IntegerField(blank=True, null=True)),
                ("vencedor_id", models.IntegerField(blank=True, null=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
