# Generated by Django 6.1.1 on 2026-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partidas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partida",
            name="carta_topo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partida",
            name="cartas_jogador1",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="partida",
            name="cartas_jogador2",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="partida",
            name="turno_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
