# Generated by Django 6.1.1 on 2026-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partidas", "0002_partida_carta_topo_partida_cartas_jogador1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partida",
            name="baralho",
            field=models.JSONField(default=list),
        ),
    ]
